/** 全47都道府県（JISコード id と nam_ja）。public/japan.topojson の properties と一致。 */
export interface Prefecture {
  id: number;
  name: string;
  region: string;
  areaType: "urban" | "suburb";
}

export const PREFECTURES: Prefecture[] = [
  { id: 1, name: "北海道", region: "北海道", areaType: "suburb" },
  { id: 2, name: "青森県", region: "東北", areaType: "suburb" },
  { id: 3, name: "岩手県", region: "東北", areaType: "suburb" },
  { id: 4, name: "宮城県", region: "東北", areaType: "urban" },
  { id: 5, name: "秋田県", region: "東北", areaType: "suburb" },
  { id: 6, name: "山形県", region: "東北", areaType: "suburb" },
  { id: 7, name: "福島県", region: "東北", areaType: "suburb" },
  { id: 8, name: "茨城県", region: "関東", areaType: "suburb" },
  { id: 9, name: "栃木県", region: "関東", areaType: "suburb" },
  { id: 10, name: "群馬県", region: "関東", areaType: "suburb" },
  { id: 11, name: "埼玉県", region: "関東", areaType: "urban" },
  { id: 12, name: "千葉県", region: "関東", areaType: "urban" },
  { id: 13, name: "東京都", region: "関東", areaType: "urban" },
  { id: 14, name: "神奈川県", region: "関東", areaType: "urban" },
  { id: 15, name: "新潟県", region: "中部", areaType: "suburb" },
  { id: 16, name: "富山県", region: "中部", areaType: "suburb" },
  { id: 17, name: "石川県", region: "中部", areaType: "suburb" },
  { id: 18, name: "福井県", region: "中部", areaType: "suburb" },
  { id: 19, name: "山梨県", region: "中部", areaType: "suburb" },
  { id: 20, name: "長野県", region: "中部", areaType: "suburb" },
  { id: 21, name: "岐阜県", region: "中部", areaType: "suburb" },
  { id: 22, name: "静岡県", region: "中部", areaType: "suburb" },
  { id: 23, name: "愛知県", region: "中部", areaType: "urban" },
  { id: 24, name: "三重県", region: "関西", areaType: "suburb" },
  { id: 25, name: "滋賀県", region: "関西", areaType: "suburb" },
  { id: 26, name: "京都府", region: "関西", areaType: "urban" },
  { id: 27, name: "大阪府", region: "関西", areaType: "urban" },
  { id: 28, name: "兵庫県", region: "関西", areaType: "urban" },
  { id: 29, name: "奈良県", region: "関西", areaType: "suburb" },
  { id: 30, name: "和歌山県", region: "関西", areaType: "suburb" },
  { id: 31, name: "鳥取県", region: "中国", areaType: "suburb" },
  { id: 32, name: "島根県", region: "中国", areaType: "suburb" },
  { id: 33, name: "岡山県", region: "中国", areaType: "suburb" },
  { id: 34, name: "広島県", region: "中国", areaType: "urban" },
  { id: 35, name: "山口県", region: "中国", areaType: "suburb" },
  { id: 36, name: "徳島県", region: "四国", areaType: "suburb" },
  { id: 37, name: "香川県", region: "四国", areaType: "suburb" },
  { id: 38, name: "愛媛県", region: "四国", areaType: "suburb" },
  { id: 39, name: "高知県", region: "四国", areaType: "suburb" },
  { id: 40, name: "福岡県", region: "九州・沖縄", areaType: "urban" },
  { id: 41, name: "佐賀県", region: "九州・沖縄", areaType: "suburb" },
  { id: 42, name: "長崎県", region: "九州・沖縄", areaType: "suburb" },
  { id: 43, name: "熊本県", region: "九州・沖縄", areaType: "suburb" },
  { id: 44, name: "大分県", region: "九州・沖縄", areaType: "suburb" },
  { id: 45, name: "宮崎県", region: "九州・沖縄", areaType: "suburb" },
  { id: 46, name: "鹿児島県", region: "九州・沖縄", areaType: "suburb" },
  { id: 47, name: "沖縄県", region: "九州・沖縄", areaType: "suburb" },
];
